config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }
  resources :gurus, only: %i[] do
    member do
      get :badge_achievements
    end
  end

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
    end
    resources :gists, only: :create
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member
      patch :publish, on: :member
      patch :unpublish, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :badges
    resources :gists, only: :index
  end

  resources :badges, only: %i[index show]

  resources :feedbacks, only: %i[new create]
  get 'feedbacks/state', as: 'state_feedback'
end

app/models/badge.rb
# frozen_string_literal: true

class Badge < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'user_id'
  belongs_to :requirement, class_name: 'BadgeRequirement'
  has_many :badge_achievements, dependent: :destroy
  has_many :given_users, through: :badge_achievements, source: :user

  validates :title, presence: true, uniqueness: true, length: { minimum: 5 }
  validates :picture, presence: true, length: { minimum: 5 }
  validate :validate_requirement_data, on: :create

  private

  def validate_requirement_data
    if (requirement_id == 1 || requirement_id == 2) && Test.find_by(id: requirement_data.to_i).nil?
      errors.add(:base, I18n.t('admin.badges.badge.test_doesnt_exist'))
    elsif requirement_id == 3 && Category.find_by(id: requirement_data.to_i).nil?
      errors.add(:base, I18n.t('admin.badges.badge.category_doesnt_exist'))
    end
  end
end

app/controllers/admin/badges_controller.rb
# frozen_string_literal: true

class Admin::BadgesController < Admin::BaseController
  before_action :find_badge, only: %i[show edit update update_inline destroy publish unpublish state]
  before_action :find_badges, only: %i[index update_inline]

  def index; end

  def new
    @badge = Badge.new
  end

  def create
    @badge = current_user.author_badges.new(badge_params)
    fill_requirement_data
    if @badge.save
      redirect_to admin_badge_path(@badge), notice: t('.success')
    else
      render :new
    end
  end

  def show; end
  def edit; end

  def update
    if @badge.update(badge_params)
      redirect_to admin_badge_path(@badge)
    else
      render :edit
    end
  end

  def destroy
    @badge.destroy
    redirect_to admin_badges_path
  end

  private

  def fill_requirement_data
    params[:badge].each do |key,value|
      if key.include?('required_') && value.present?
        @badge.requirement_data = value
        return
      end
    end
  end

  def find_badge
    @badge = Badge.find(params[:id])
  end

  def find_badges
    @badges = Badge.all
  end

  def badge_params
    params.require(:badge).permit(:title, :picture, :requirement_id)
  end
end

app/controllers/badges_controller.rb
# frozen_string_literal: true

class BadgesController < ApplicationController
  def index
    @badges = Badge.all
  end

  def show
    @badge = Badge.find(params[:id])
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
  def badge_header(badge)
    badge.persisted? ? I18n.t('admin.badges.edit.header') : I18n.t('admin.badges.new.header')
  end
end

app/views/admin/badges/_badge.html.erb
<div class="row table-border">
  <div class="col-md-4 table-border">
    <%= badge.title %>
  </div>
  <div class="col-md-4 table-border" align="center">
    <img src="<%= badge.picture %>">
  </div>
  <div class="col-md-4 table-border">
    <div class="row">
      <div class="col-md-4 col-4" align="center">
        <%= link_to t('admin.author_actions.watch'), admin_badge_path(badge), method: :get %>
      </div>
      <div class="col-md-4 col-4" align="center">
        <%= link_to t('admin.author_actions.edit'), edit_admin_badge_path(badge), method: :get %>
      </div>
      <div class="col-md-4 col-4" align="center">
        <%= link_to t('admin.author_actions.delete'), admin_badge_path(badge), method: :delete, data: { confirm: t('.delete_confirmation') }, style: "color: red;" %>
      </div>
    </div>
  </div>
</div>

app/views/admin/badges/_form.html.erb
<span class="hide badge-new-js"></span>
<h2><%= badge_header(@badge) %></h2>

<%= form_with model: [:admin, @badge], local: true do |form| %>
  <%= render 'shared/errors', instance: @badge %>

  <div class="mb-3">
    <div><%= form.label :title %></div>
    <div><%= form.text_area :title, cols: 45, rows: 1 %></div>
  </div>

  <div class="mb-3">
    <div><%= form.label :picture %></div>
    <div><%= form.text_area :picture, cols: 45, rows: 1 %></div>
  </div>

  <div class="mb-3" id="badge_requirement_select">
    <div><%= form.label :requirement_id %></div>
    <div><%= form.collection_select :requirement_id, BadgeRequirement.order(:id), :id, :description %></div>
  </div>

  <div class="mb-3 select-requirement" id="required_test" style="display: none;">
    <div><%= form.label :required_test_id %></div>
    <div><%= form.collection_select :required_test_id, Test.order(:id), :id, :title, prompt: true %></div>
  </div>

  <div class="mb-3 select-requirement" id="required_category" style="display: none;">
    <div><%= form.label :required_category_id %></div>
    <div><%= form.collection_select :required_category_id, Category.order(:id), :id, :title, prompt: true %></div>
  </div>

  <div class="mb-3 select-requirement" id="required_percent" style="display: none;">
    <div><label for="badge_required_percent"><%= t('activerecord.attributes.badge.required_percent') %></label></div>
    <div><select name="badge[required_percent]" id="badge_required_percent">
      <option value="">Пожалуйста, выберите</option>
      <option value="50">50%</option>
      <option value="100">100%</option>
    </select></div>
  </div>

  <div class="mt-5"><%= form.submit %></div></p>
<% end %>

app/views/admin/badges/edit.html.erb
<% if @badge.requirement_id == 1 || @badge.requirement_id == 2 %>
  <div class="hide info-required-id" data-required-id="<%= Test.where('id < ?', @badge.requirement_data).count + 1 %>"></div>
<% elsif @badge.requirement_id == 3 %>
  <div class="hide info-required-id" data-required-id="<%= Category.where('id < ?', @badge.requirement_data).count + 1 %>"></div>
<% elsif @badge.requirement_id == 4 %>
  <div class="hide info-required-id" data-required-id="<%= @badge.requirement_data.to_i / 50 %>"></div>
<% end %>

<div class="row table-border">
  <div class="col-md-8 table-border">
    <%= render 'form' %>
  </div>
  <div class="col-md-4 table-border">
    <div><%= link_to t('.back'), admin_badges_path, method: :get %></div>
    <div><%= link_to t('.watch'), admin_badge_path(@badge), method: :get %></div>
    <div><%= link_to t('.delete'), admin_badge_path(@badge), method: :delete, data: { confirm: t('.delete_confirmation')}, style: "color: red" %></div>
  </div>
</div>

app/views/admin/badges/index.html.erb
<div class="row table-border">
  <div class="col-md-8 table-border" align="center">
    <%= t('.header') %>
  </div>
  <div class="col-md-4 table-border">
    <%= link_to t('.new'), new_admin_badge_path, method: :get %>
  </div>
</div>
<div class="row  table-border" align="center">
  <div class="col-md-4 table-border">
    <%= t('.title') %>
  </div>
  <div class="col-md-4 table-border">
    <%= t('.picture') %>
  </div>
  <div class="col-md-4 table-border">
    <%= t('admin.author_actions.header') %>
  </div>
</div>
<div id="table-with-values">
  <%= render @badges %>
</div>

app/views/admin/badges/new.html.erb
<div class="row table-border">
  <div class="col-md-8 table-border">
    <%= render 'form' %>
  </div>
  <div class="col-md-4 table-border">
    <%= link_to t('.back'), admin_badges_path, method: :get %>
  </div>
</div>

app/views/admin/badges/show.html.erb
<div class="row table-border">
  <div class="col-md-8 table-border">
    <div><%= t('.title') %>: <%= @badge.title %></div>
    <div><%= t('.picture') %>: <%= @badge.picture %></div>
    <div><%= t('.author') %>: <%= @badge.author.first_name %> <%= @badge.author.last_name %></div>
    <div><%= t('.requirements') %>: <%= @badge.requirement.description %></div>
    <div><%= t('.requirements_data') %>: <%= @badge.requirement_data %></div>
  </div>
  <div class="col-md-4 table-border">
    <div><%= link_to t('.back'), admin_badges_path, method: :get %></div>
    <div><%= link_to t('.edit'), edit_admin_badge_path(@badge), method: :get %></div>
  </div>
</div>