config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }
  resources :gurus, only: %i[] do
    member do
      get :badge_achievements
    end
  end

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
    end
    resources :gists, only: :create
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member
      patch :publish, on: :member
      patch :unpublish, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :badges
    resources :gists, only: :index
  end

  resources :badges, only: %i[index show]

  resources :feedbacks, only: %i[new create]
  get 'feedbacks/state', as: 'state_feedback'
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :test_passages, dependent: :destroy, foreign_key: 'current_question_id'
  has_many :gists, dependent: :destroy

  validates :body, presence: true, length: { minimum: 5 }
end

app/models/test_passage.rb
# frozen_string_literal: true

class TestPassage < ApplicationRecord
  TEST_SUCCESSFULLY_COMPLETE_MIN_PERCENT = 85

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_first_question, on: :create

  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)
    self.current_question = test.questions.order(:id).where('id > ?', current_question.id).first
    save!
  end

  def completed?
    current_question.nil?
  end

  def check_successful
    update(successful: true) if success?
  end

  def complete_percent
    ((correct_questions / test.questions.count.to_f) * 100).to_i
  end

  def success?
    complete_percent >= TEST_SUCCESSFULLY_COMPLETE_MIN_PERCENT
  end

  def current_question_number
    test.questions.where('id <= ?', current_question.id).count
  end

  def questions_count
    test.questions.count
  end

  def expired?
    return false if self.test.time.nil?

    time_passed > self.test.time * 60
  end

  def time_left
    return nil if self.test.time.nil?

    (test.time * 60) - time_passed
  end

  private

  def before_validation_set_first_question
    self.current_question = test.questions.first
  end

  def correct_answer?(answer_ids)
    answer_ids.nil? ? false : correct_answers.ids.sort == answer_ids.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.corrects
  end

  def time_passed
    (Time.current - created_at).to_i
  end
end

app/controllers/test_passages_controller.rb
# frozen_string_literal: true

class TestPassagesController < ApplicationController
  before_action :find_test_passage, only: %i[show update result gist]

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_test_passage_not_found

  def show
    stop_passage if @test_passage.expired?
    redirect_to result_test_passage_path(@test_passage) if @test_passage.current_question.nil?
  end

  def update
    @test_passage.accept!(params[:answer_ids])
    stop_passage if @test_passage.expired?
    if @test_passage.completed?
      @test_passage.check_successful
      BadgeAchievementService.new(@test_passage).call if @test_passage.check_successful
      TestsMailer.completed_test(@test_passage).deliver_now if @test_passage.successful
      redirect_to result_test_passage_path(@test_passage)
    else
      render :show
    end
  end

  def result
    redirect_to test_passage_path(@test_passage) unless @test_passage.completed?
  end

  private

  def find_test_passage
    @test_passage = TestPassage.find(params[:id])
  end

  def stop_passage
    @test_passage.update(current_question: nil)
  end

  def rescue_with_test_passage_not_found
    render plain: "Ошибка: Прохождение теста не найдено"
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
end

app/views/test_passages/result.html.erb
<div class="row table-border">
  <div class="col-md-12">
    <div>
      <div class="row">
          <div class="col-md-3">
            <%= t('.header') %>:
          </div>
        <div class="col-md-9">
          <b><%= @test_passage.test.title %></b>
        </div>
      </div>
    </div>
    <div>
      <div class="mt-5 mb-5" align="center">
      <% if @test_passage.success? %>
        <h3 style="background-color: lime;">
          <%= t('.success', complete_percent: @test_passage.complete_percent) %>
        </h3>
      <% else %>
        <h3 style="background-color: orange;">
          <%= t('.failure', complete_percent: @test_passage.complete_percent) %>
        </h3>
      <% end %>
      </div>
    </div>
    <div>
      <% if BadgeAchievement.awards(@test_passage).present? %>
        <div class="row text-center justify-content-center mb-3">
          <%= t('.awarded_with_badges') %>
        </div>
        <% BadgeAchievement.awards(@test_passage).each do |badge_achievement| %>
          <div class="row text-center justify-content-center">
            <div class="col-md-6 mb-3">
                <img src="<%= badge_achievement.badge.picture %>">
            </div>
          </div>
        <% end %>
        <div class="mb-3" align="center">
         <%= link_to t('.my_badges'), badge_achievements_guru_path(current_user) %> /
         <%= link_to t('.all_badges'), badges_path %>
        </div>
      <% end %>
    </div>
    <div>
      <%= link_to t('.back'), tests_path, method: :get %>
    </div>
  </div>
</div>

app/views/test_passages/show.html.erb
<span class="hide info-progress"
      data-current-progress="<%= @test_passage.current_question_number %>"
      data-maximum-progress="<%= @test_passage.questions_count %>">
</span>
<span class="hide info-time-left timer-js"
      data-time-left="<%= @test_passage.time_left %>">
</span>

<div class="row table-border">
  <div class="col-md-12">
    <div>
      <div class="row">
          <div class="col-md-3">
            <%= t('.header') %>
          </div>
        <div class="col-md-6">
          <b><%= @test_passage.test.title %></b>
        </div>
        <div class="test-timer col-md-3" style="display: none;">
          <%= t('.timer') %>: <span id=test_timer_string></span>
        </div>
      </div>
      <div class="mt-2 mb-4">
        <!-- html + js realization with data from erb -->
        <div class="js-progress">
          <div class="js-progress-bar-overal">
            <div class="js-progress-bar-current"></div>
          </div>
        </div>
        <!-- erb + bootstrap realization -->
        <div class="progress" style="display: none;">
          <div class="progress-bar" role="progressbar" style="width: <%= @test_passage.current_question_number.to_f * 100 / @test_passage.questions_count %>%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
        </div>
      </div>
    </div>
    <div id="input_form">
      <p><%= t('.question_number', current_question_number: @test_passage.current_question_number, questions_count: @test_passage.questions_count) %> <b><%= @test_passage.current_question.body %></b></p>
      <%= form_with url: test_passage_path(@test_passage), method: :put, local: true do |form| %>
        <%= form.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :body, include_hidden: false do |b| %>
          <p>
            <%= b.check_box id: "answer_ids_#{b.object.id}" %>
            <%= b.label %>
          </p>
        <% end %>
        <hr>
        <div class="row">
          <div class="col-md-6" align="left">
            <%= form.submit t('.next_question') %>
          </div>
          <div class="col-md-6"  align="right">
            <%= link_to t('.create_gist'), test_passage_gists_path(@test_passage), method: :post %>
          </div>
        </div>
      <% end %>
    </div>
    <br>
    <div>
      <%= link_to t('.back'), tests_path, method: :get, data: { confirm: t('.back_confirmation') } %>
    </div>
  </div>
</div>