config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }
  resources :gurus, only: %i[] do
    member do
      get :badge_achievements
    end
  end

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
    end
    resources :gists, only: :create
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member
      patch :publish, on: :member
      patch :unpublish, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :badges
    resources :gists, only: :index
  end

  resources :badges, only: %i[index show]

  resources :feedbacks, only: %i[new create]
  get 'feedbacks/state', as: 'state_feedback'
end

app/views/shared/_admin_nav.html.erb
<div class="row admin-nav align-items-center">
  <div class="col-lg-6 col-sm-12">
    <div class="d-flex justify-content-start align-items-center">
      <div class="p-2"><%= link_to 'TestGuru', root_path, { class: 'brand-link' } %></div>
      <div class="dropdown me-3">
        <button class="btn btn-secondary" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
          <%= octicon 'multi-select', height: '32' %>
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
          <li><a class="dropdown-item" href="<%= tests_path %>"><%= t('shared.nav.tests') %></a></li>
          <li><a class="dropdown-item" href="<%= badges_path %>"><%= t('shared.nav.badges') %></a></li>
        </ul>
      </div>
      <div class="p-2"><%= link_to 'Admin', admin_tests_path, { class: 'brand-link' } %></div>
      <div class="dropdown me-3">
        <button class="btn btn-secondary" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
          <%= octicon 'multi-select', height: '32' %>
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
          <li><a class="dropdown-item" href="<%= admin_tests_path %>"><%= t('shared.nav.tests') %></a></li>
          <li><a class="dropdown-item" href="<%= admin_badges_path %>"><%= t('shared.nav.badges') %></a></li>
          <li><hr class="dropdown-divider"></li>
          <li><a class="dropdown-item" href="<%= admin_gists_path %>"><%= t('shared.nav.gists') %></a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="col-lg-6 col-sm-12">
    <div class="d-flex justify-content-end align-items-center">
      <div class="p-2"><%= button_to 'ru', admin_tests_path, method: :get, params: { lang: "ru" } %></div>
      <div class="p-2 me-3"><%= button_to 'en', admin_tests_path, method: :get, params: { lang: "en" } %></div>
      <% if user_signed_in? %>
        <div class="p-2">
          <div align="right"><%= t('shared.nav.guru') %> <b><%= current_user.first_name %></b></div>
        </div>
        <div class="dropdown">
          <button class="btn btn-secondary" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
            <%= octicon 'gear' %>
          </button>
          <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
            <li><a class="dropdown-item" href="<%= badge_achievements_guru_path(current_user) %>"><%= t('shared.nav.my_badges') %></a></li>
            <li><hr class="dropdown-divider"></li>
            <li><%= link_to t('shared.nav.exit'), destroy_user_session_path, { method: :delete, data: { confirm: t('shared.nav.confirm') }, class: 'dropdown-item' } %></li>
          </ul>
        </div>
      <% else %>
        <div class="p-2">
          <div align="right"><%= link_to t('shared.nav.sign_up'), new_user_registration_path, { class: 'no-decoration-link' } %></div>
          <div align="right"><%= link_to t('shared.nav.sign_in'), new_user_session_path, { class: 'no-decoration-link' } %></div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if instance && instance.errors.present? %>
  <%= content_tag :div, class: 'instance-errors', data: { instance_id: instance.id }, style: 'color: red;' do %>
    <h3><%= t('.header', count: instance.errors.count) %></h3>
    <ul>
      <% instance.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
<% end %>

app/views/shared/_flash.html.erb
<div class="flash-push" align="center">
  <% flash.each do |key, message| %>
    <% if key == "alert" %>
      <%= content_tag :p, message, class: "alert alert-danger" %>
    <% elsif key == "notice" %>
      <%= content_tag :p, message, class: "alert alert-primary" %>
    <% elsif key == "notice_html" %>
      <%= content_tag :p, message.html_safe, class: "alert alert-primary" %>
    <% else %>
      <%= content_tag :p, message, class: "alert alert-dark" %>
    <% end %>
  <% end %>
</div>

app/views/shared/_nav.html.erb
<div class="row user-nav align-items-center">
  <div class="col-lg-6 col-sm-12">
    <div class="d-flex justify-content-start align-items-center">
      <div class="p-2"><%= link_to 'TestGuru', root_path, { class: 'brand-link' } %></div>
      <div class="dropdown me-3">
        <button class="btn btn-secondary" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
          <%= octicon 'multi-select', height: '32' %>
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
          <li><a class="dropdown-item" href="<%= tests_path %>"><%= t('shared.nav.tests') %></a></li>
          <li><a class="dropdown-item" href="<%= badges_path %>"><%= t('shared.nav.badges') %></a></li>
        </ul>
      </div>
      <% if admin? %>
        <div class="p-2"><%= link_to 'Admin', admin_tests_path, { class: 'brand-link' } %></div>
        <div class="dropdown me-3">
          <button class="btn btn-secondary" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
            <%= octicon 'multi-select', height: '32' %>
          </button>
          <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
            <li><a class="dropdown-item" href="<%= admin_tests_path %>"><%= t('shared.nav.tests') %></a></li>
            <li><a class="dropdown-item" href="<%= admin_badges_path %>"><%= t('shared.nav.badges') %></a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="<%= admin_gists_path %>"><%= t('shared.nav.gists') %></a></li>
          </ul>
        </div>
      <% end %>
    </div>
  </div>
  <div class="col-lg-6 col-sm-12">
    <div class="d-flex justify-content-end align-items-center">
      <% if user_signed_in? %>
        <div class="p-2"><%= button_to 'ru', tests_path, method: :get, params: { lang: "ru" } %></div>
        <div class="p-2 me-3"><%= button_to 'en', tests_path, method: :get, params: { lang: "en" } %></div>
        <div class="p-2">
          <div align="right"><%= t('shared.nav.guru') %> <b><%= current_user.first_name %></b></div>
        </div>
        <div class="dropdown">
          <button class="btn btn-secondary" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
            <%= octicon 'gear' %>
          </button>
          <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
            <li><a class="dropdown-item" href="<%= badge_achievements_guru_path(current_user) %>"><%= t('.my_badges') %></a></li>
            <li><hr class="dropdown-divider"></li>
            <li><%= link_to t('shared.nav.exit'), destroy_user_session_path, { method: :delete, data: { confirm: t('shared.nav.confirm') }, class: 'dropdown-item' } %></li>
          </ul>
        </div>
      <% else %>
        <div class="p-2"><%= button_to 'ru', new_user_session_path, method: :get, params: { lang: "ru" } %></div>
        <div class="p-2 me-5"><%= button_to 'en', new_user_session_path, method: :get, params: { lang: "en" } %></div>
        <div class="p-2">
          <div align="right"><%= link_to t('shared.nav.sign_up'), new_user_registration_path, { class: 'no-decoration-link' } %></div>
          <div align="right"><%= link_to t('shared.nav.sign_in'), new_user_session_path, { class: 'no-decoration-link' } %></div>
        </div>
      <% end %>
    </div>
  </div>
</div>