config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }
  resources :gurus, only: %i[] do
    member do
      get :badge_achievements
    end
  end

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
    end
    resources :gists, only: :create
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member
      patch :publish, on: :member
      patch :unpublish, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :badges
    resources :gists, only: :index
  end

  resources :badges, only: %i[index show]

  resources :feedbacks, only: %i[new create]
  get 'feedbacks/state', as: 'state_feedback'
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :test_passages, dependent: :destroy, foreign_key: 'current_question_id'
  has_many :gists, dependent: :destroy

  validates :body, presence: true, length: { minimum: 5 }
end

app/controllers/admin/questions_controller.rb
# frozen_string_literal: true

class Admin::QuestionsController < Admin::BaseController
  before_action :find_question, only: %i[show edit update destroy]
  before_action :find_test, only: %i[new create]
  before_action :check_test_published, only: %i[new create edit update destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_question_not_found

  def new
    @question = @test.questions.new
  end

  def create
    @question = @test.questions.new(question_params)
    if @question.save
      redirect_to admin_question_path(@question)
    else
      render :new
    end
  end

  def show; end
  def edit; end

  def update
    if @question.update(question_params)
      redirect_to admin_question_path(@question)
    else
      render :edit
    end
  end

  def destroy
    @question.destroy
    redirect_to admin_test_path(@question.test)
  end

  private

  def find_question
    @question = Question.find(params[:id])
  end

  def find_test
    @test = Test.find(params[:test_id])
  end

  def check_test_published
    test = @test || @question.test
    redirect_to admin_test_path(test), alert: t('admin.tests.frozen') and return if test.published
  end

  def question_params
    params.require(:question).permit(:body)
  end

  def rescue_with_question_not_found
    render plain: "Ошибка: Вопрос или вопросы не найдены"
  end
end

app/helpers/questions_helper.rb
# frozen_string_literal: true

module QuestionsHelper
  def question_header
    text = @question.persisted? ? I18n.t('.admin.questions.edit.header') : I18n.t('.admin.questions.new.header')
    text.concat(" \"#{@question.test.title}\"")
  end
end

app/views/admin/questions/_form.html.erb
<h2><%= question_header %></h2>

<%= form_with model: [:admin, @test, @question], local: true do |form| %>
  <%= render 'shared/errors', instance: @question %>

  <p>
    <div><%= form.label :body, t('.body') %></div>
    <div><%= form.text_area :body, cols: 45, rows: 5 %></div>
  </p>

  <br><p><div><%= form.submit %></div></p>
<% end %>

app/views/admin/questions/_question.html.erb
<div class="row table-border">
  <div class="col-md-8 table-border" align="left">
    <%= question.body %>
  </div>
  <div class="col-md-4 table-border">
    <div class="row">
      <div class="col-md-4" align="center">
        <%= link_to t('admin.author_actions.watch'), admin_question_path(question), method: :get %>
      </div>
      <div class="col-md-4" align="center">
        <%= link_to t('admin.author_actions.edit'), edit_admin_question_path(question), method: :get %>
      </div>
      <div class="col-md-4" align="center">
        <%= link_to t('admin.author_actions.delete'), admin_question_path(question), method: :delete, data: { confirm: t('admin.author_actions.delete_confirmation')}, style: "color: red" %>
      </div>
    </div>
  </div>
</div>

app/views/admin/questions/edit.html.erb
<div class="row table-border">
  <div class="col-md-8 table-border">
    <%= render 'form' %>
  </div>
  <div class="col-md-4 table-border">
    <div><%= link_to t('.back'), admin_test_path(@question.test), method: :get %></div>
    <div><%= link_to t('.watch'), admin_question_path(@question), method: :get %></div>
    <div><%= link_to t('.delete'), admin_question_path(@question), method: :delete, data: { confirm: t('.delete_confirmation')}, style: "color: red" %></div>
  </div>
</div>

app/views/admin/questions/new.html.erb
<div class="row table-border">
  <div class="col-md-8 table-border">
    <%= render 'form' %>
  </div>
  <div class="col-md-4 table-border">
    <%= link_to t('.back'), admin_test_path(@question.test), method: :get %>
  </div>
</div>

app/views/admin/questions/show.html.erb
<div class="row table-border">
  <div class="col-md-8 table-border">
    <div>
      <h2><%= t('.header', title: @question.test.title) %>:</h2>
      <p>
      <div style="border: 1px solid lightgray; padding: 5px;">
        <%= @question.body %>
      </div>
        
      </p>
    </div>
  </div>
  <div class="col-md-4 table-border">
    <div><%= link_to t('.back'), admin_test_path(@question.test), method: :get %></div>
    <div><%= link_to t('.edit'), edit_admin_question_path(@question), method: :get %></div>
    <div><%= link_to t('.add_answer'), new_admin_question_answer_path(@question), method: :get %></div>
  </div>
</div>
<div class="row  table-border" align="center">
  <div class="col-md-8 table-border">
    <%= t('.answers') %>
  </div>
  <div class="col-md-4 table-border">
    <%= t('admin.author_actions.header') %>
  </div>
</div>
<%= render @question.answers %>